services:
  - type: web
    name: searxng
    env: docker
    plan: free
    autoDeploy: true
    ports:
      - 8080
    envVars:
      - key: SEARXNG_SECRET_KEY
        value: "change_this_to_any_random_string_12345"