services:
  - type: web
    name: searxng
    env: docker
    plan: free
    autoDeploy: true
    ports:
      - 8080
    volumes:
      - name: searxng-config
        mountPath: /etc/searxng
      - name: searxng-logo
        mountPath: /usr/local/searxng/searx/static/themes/simple/img/searxng.png
        sourcePath: ./searxng.png