use_default_settings: false

general:
  instance_name: "Cipher"

server:
  bind_address: 0.0.0.0
  port: 8080
  secret_key: "REPLACE_WITH_RANDOM_SECRET_KEY"
  base_url: false

search:
  safe_search: 0
  formats:
    - html
    - json

engines:
  - name: google
    disabled: false

  - name: google suggestions
    disabled: false

ui:
  default_locale: en
  query_in_title: true
  default_theme: simple

  theme_args:
    simple_style: light

  center_alignment: true
  url_formatting: pretty

categories_as_tabs: {}
